# Generated by Django 4.2.13 on 2024-06-06 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0002_item_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=128)),
                ('population', models.PositiveIntegerField()),
                ('capital', models.CharField(max_length=128)),
                ('language', models.CharField(max_length=128)),
            ],
        ),
    ]
